name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Execute Script on Server
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run script on server
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash /home/bot/vending_machines_bot/restart.sh'