name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Execute Script on Server
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

      - name: Test connection through proxy
        run: curl -x http://${{ secrets.PROXY_USER }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_HOST }}:${{ secrets.PROXY_PORT }} http://${{ secrets.SSH_HOST }}

      # Настройка SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host remote-server\n  HostName ${{ secrets.SSH_HOST }}\n  User ${{ secrets.SSH_USER }}\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no" > ~/.ssh/config

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Выполнение скрипта на сервере
      - name: Run script on server
        env:
          http_proxy: http://${{ secrets.PROXY_USER }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_HOST }}:${{ secrets.PROXY_PORT }}
          https_proxy: http://${{ secrets.PROXY_USER }}:${{ secrets.PROXY_PASSWORD }}@${{ secrets.PROXY_HOST }}:${{ secrets.PROXY_PORT }}
        run: ssh remote-server 'bash /home/bot/vending_machines_bot/restart.sh'