name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Execute Script on Server
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Check out the repository
        uses: actions/checkout@v4

      # Настройка SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host remote-server\n  HostName ${{ secrets.SSH_HOST }}\n  User ${{ secrets.SSH_USER }}\n  IdentityFile ~/.ssh/id_ed25519\n  StrictHostKeyChecking no" > ~/.ssh/config

      # Выполнение скрипта на сервере
      - name: Run script on server
        run: ssh remote-server 'bash /home/bot/vending_machines_bot/restart.sh'